#!/usr/bin/python

from epguide.common import Config
from epguide.epguide import EpGuide
import sys

def RunEpguide():
    """
    glowna petla aplikacji, odczytuje konfiguracje, uruchamia operacje
    """
    config = Config()
    config.ParseCommandLine(sys.argv)
    if config.options.use_config:
        config.ReadConfigFile()

    epguide = EpGuide(config)
    epguide.Execute()

if __name__ == '__main__':
    RunEpguide()
    